language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

before_script:
  - "npm i -g gatsby"
  - "npm i"

# Run mocha tests
script:
  - "npm run test"

# https://docs.travis-ci.com/user/deployment-v2/providers/netlify/
deploy:
  provider: netlify
  edge: true # opt in to dpl v2
  auth: NETLIFY_AUTH_TOKEN=<auth>
  site: NETLIFY_SITE_ID=<site>
  cleanup: true
  on:
    branch: deploy

notifications:
  slack: superluigibrospizza:Y1lW96ZU0ir2XFBSnfrBTvXU
