language: node_js

node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - "npm i -g gatsby"
  - "npm i"
# Run mocha tests
script:
  - "npm run test"
# https://docs.travis-ci.com/user/deployment-v2/providers/netlify/

env:
  - NETLIFY_SITE_ID=<site>
  - NETLIFY_AUTH_TOKEN=<auth>

deploy:
  provider: netlify
  edge: true # opt in to dpl v2
  site: <site>
  auth: <auth>
  cleanup: true
  message: "Deploy triggered by Travis CI"
  on:
    branch: deploy
notifications:
  slack: superluigibrospizza:Y1lW96ZU0ir2XFBSnfrBTvXU
