/**
 * @function linkResolver
 * @param {object} document - The document that is passed has a type that's defined by the custom type created in the HMBK Prismic Repo
 * @returns {string}  - returns one of two things: the link generated by uid of the document's page OR the index route, '/'
 */

const linkResolver = (document) => {
  if (document.type === "page") {
    return `/${document.uid}`;
  }
  return "/";
};

export default linkResolver;
