name: Create Issue Branch
on:
  issues:
    types: [assigned]
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        id: Create_Issue_Branch
        uses: robvanderleek/create-issue-branch@issue-201-Feature_request_provide_the_final_branch_name_as_an_action_output
        branchName: short
        branches:
          - label:
              - bug
              - data/CMS
              - data/functions
              - deploy
              - design/cosmetic
              - design/layout
              - design/storybook
              - documentation
              - feature
            name: deploy
          - label: bug
            prefix: fix/
          - label:
              - data/CMS
              - data/functions
            prefix: data/
          - label:
              - design/cosmetic
              - design/layout
            prefix: style/
          - label: documentation
            prefix: docs/
          - label: feature
            prefix: feat/
          - label: wontfix
            skip: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo branch name
        run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}
