name: Scheduled Build

on:
  schedule:
    - cron: "15 10 * * *"
    - cron: "15 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger an HMBK build on Netlify
        run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_CRON_DEPLOY_TOKEN }}
